[metadata.heroku]
  root-package = "github.com/annakertesz/cp-music-lib"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.12.0"

[prune]
  go-tests = true
  unused-packages = true
