[metadata.heroku]
  root-package = "github.com/annakertesz/cp-music-lib"
  go-version = "go1.8.3"
    install = [ "./cmd/..."]
    ensure = "true"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.12.0"

[prune]
  go-tests = true
  unused-packages = true
